### ISSUE TITLE
这是一个app么?

### ISSUE THREAD

**Issue by liuxiaotong15** [GavinAndre/JNIDemo#1]
这个是要如何跑起来?

**Comment by GavinAndre** [comment]
编译完了就能跑了

**Comment by liuxiaotong15** [comment]
请问是用android studio么? 我编出来了apk 为什么安不到手机上呢?我是在小米9上进行的测试,报了 安装失败 -103 安装包解析出错

**Comment by liuxiaotong15** [comment]
最后发现是我 android studio 问题, 参考下面链接解决,多谢.
https://stackoverflow.com/questions/27541838/android-studio-gradle-already-disposed-module
